# Generated by Django 4.2.17 on 2025-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemodel',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
