# Generated by Django 4.2.17 on 2025-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roomcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gallery',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
