# Generated by Django 4.2.17 on 2025-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('super_admin', 'Super Admin'), ('store_owner', 'Store Owner'), ('staff', 'Staff')], max_length=20, unique=True, verbose_name='Permission Type')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.permission', verbose_name='Permissions'),
        ),
    ]
