# Generated by Django 4.2.17 on 2025-03-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_id_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
